server:
  port: 8080

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users-operations
          uri: lb://users-ws
          predicates:
            - Path=/users/**
            - Method=GET,POST,PUT,DELETE
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
        - id: users-h2-console
          uri: lb://users-ws
          predicates:
            - Path=/h2-console
            - Method=GET
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
